site_name: "Eucalypt: liquiYAML"
repo_url: https://github.com/curvelogic/eucalypt
copyright: "Copyright (C) 2018 Greg Hawkins"
docs_dir: docs
pages:
- Home: index.md
- Getting Started: getting-started.md
- Syntax: syntax.md
- Command Line: command-line.md
- Philosophy: philosophy-lang.md
markdown_extensions:
  - admonition
  - footnotes
theme: readthedocs
