# Generate and push test harness image
version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: |
            docker build -t eucalypt-test-harness .
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker login -u $DOCKER_USER -p $DOCKER_PASS
              docker tag eucalypt-test-harness "curvelogic/eucalypt-test-harness:${CIRCLE_SHA1}"
              docker push "curvelogic/eucalypt-test-harness:${CIRCLE_SHA1}"
              docker tag eucalypt-test-harness "curvelogic/eucalypt-test-harness:latest"
            fi
